on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@HEAD
    - uses: docker://trini/u-boot-gitlab-ci-runner:jammy-20240125-12Feb2024
      with:
        args: tools/buildman/buildman
